language: php
<<<<<<< HEAD

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose
=======
php:
  - 5.4
  - 5.5
  - 5.6
>>>>>>> 2581320... Added Travis file
